services:
  - type: web
    name: geotracker-backend
    env: docker
    plan: free
    branch: main
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false   # (You already have this in Render dashboard)
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
